SERVER:
  HOST: 0.0.0.0
  PORT: 8080

DATABASE:
  NAME: "iitkcoin.db"
  USER: "dbuser"
  PASS: "dbpassword"

WALLET:
  UPPER_COIN_LIMIT: 10000

TAX:
  INTER_BATCH: 2
  INTRA_BATCH: 33

JWT:
  PRIVATE_KEY: "this-is-a-secret"
  EXPIRATION_TIME_IN_MIN: 10
  COOKIE_NAME: "token"

LOGGER:
  LOG_LEVEL: 5 # Error: 2, Warn: 3, Info: 4, Debug: 5

FRONTEND:
  URL: "http://localhost:3000"

MAIL: 
  # IITK 
  # FROM: ""
  # PASSWORD: ""
  # HOST: "mmtp.iitk.ac.in"
  # PORT: "25"

  # Gmail
  FROM: "example@gmail.com"
  PASSWORD: "password"
  HOST: "smtp.gmail.com"
  PORT: "587"